export const shortcuts = [
    {title:"Find", shortcut: "CTRL + F"}, 
    {title:"Find And Replace", shortcut: "CTRL + H"}, 
    {title:"Word Wrap", shortcut: "CTRL + B"}, 
    {title:"Settings", shortcut: "CTRL + SHIFT + S"}, 
    {title:"Command Pallete", shortcut: "CTRL + F1"}, 
    {title:"Copy", shortcut: "CTRL + C"},
    {title:"Paste", shortcut: "CTRL + V"}, 
    {title:"Cut", shortcut: "CTRL + X"}, 
    {title:"Select All", shortcut: "CTRL + A"}, 
    {title:"Formate Document", shortcut: "CTRL + SHIFT + I"}, 
    {title:"Change All Accurrences", shortcut: "CTRL + F2"},
    {title:"Reset Code", shortcut: "CTRL + 1"}, 
    {title:"Download Code", shortcut: "CTRL + SHIFT + D"},
    {title:"Copy Line Down", shortcut: "CTRL+SHIFT+DownArrow"}, 
    {title:"Copy Line Up", shortcut: "CTRL + SHIFT + UpArrow"},
    {title:"Comment Line", shortcut: "CTRL + /"}, 
    {title:"UnComment Line", shortcut: "CTRL + /"}, 
    {title:"Add Selection to Next Match", shortcut: "CTRL + D"},
    {title:"Undo", shortcut: "CTRL + Z"}, 
    {title:"Redu", shortcut: "CTRL + Y"}, 
    {title:"Move Line Down", shortcut: "ALT + DownArrow"},
    {title:"Move Line Up", shortcut: "CTRL + UpArrow"}, 
    {title:"Go to Symbol", shortcut: "CTRL + SHIFT + O"}, 
    {title:"Rename Symbol", shortcut: "F2"}, 
    {title:"Delete Line", shortcut: "CTRL + SHIFT + K"}, 
    
]